language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

before_install:
  - composer self-update

before_script:
  - travis_retry composer install

script:
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=UTF-8 src/ --colors -n -p -s
  - ./vendor/bin/phpcpd --exclude test src/
  - ./vendor/bin/phpmd src/ text codesize,unusedcode --suffixes .php
  - ./vendor/bin/phpunit test/

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email: false