services:
  fixture.loader.file_loader:
    class: Fixture\Loader\FileLoader

  fixture.parser.json_parser:
    class: Fixture\Parser\JSONParser

  fixture.parser.yaml_parser:
    class: Fixture\Parser\YAMLParser

  fixture.parser.xml_parser:
    class: Fixture\Parser\XMLParser

  #TODO Move database pass to configuration
  fixture.driver.pdo_driver:
    class: Fixture\Driver\PDODriver
    arguments:
      - "fixture"
      - "172.22.0.2"
      - "3306"
      - "admin"
      - "secret"

  fixture.factory.loader_factory:
    class: Fixture\LoaderFactory
    arguments:
      - '@fixture.loader.file_loader'

  fixture.factory.parser_factory:
    class: Fixture\ParserFactory
    arguments:
      - '@fixture.parser.yaml_parser'
      - '@fixture.parser.json_parser'
      - '@fixture.parser.xml_parser'

  fixture.factory.driver_factory:
    class: Fixture\DriverFactory
    arguments:
      - '@fixture.driver.pdo_driver'

  fixture.loader:
    class:  Fixture\LoaderInterface
    factory: 'fixture.factory.loader_factory:getLoader'
    arguments:
        - "%fixture_loader%"

  fixture.parser:
    class:  Fixture\ParserInterface
    factory: 'fixture.factory.parser_factory:getParser'
    arguments:
        - "%fixture_parser%"

  fixture.driver:
    class:  Fixture\DriverInterface
    factory: 'fixture.factory.driver_factory:getDriver'
    arguments:
        - "%fixture_driver%"

  fixture.command.fixture_command:
    class: Fixture\Bridge\Symfony\Command\FixtureCommand
    arguments:
      - '@fixture.loader'
      - '@fixture.parser'
      - '@fixture.driver'
      - '%fixture_path%'
    tags:
      - { name: 'console.command', command: 'fixture:load' }